import { ArrowUpRight, Linkedin, Mail, MapPin, Phone } from 'lucide-react'
import { ContactForm } from '../components/ContactForm'
import { profile } from '../data/profile'

export function Contact() {
  return <section id="contact" className="section contact story-section">
    <p className="eyebrow">07 / THE NEXT CHAPTER</p>
    <div className="contact-title"><h2>LET’S BUILD<br/>SOMETHING<br/><span>USEFUL.</span></h2><p>I’m looking for an entry-level opportunity where I can help people, keep systems connected and reliable, and continue learning through practical work.</p></div>
    <div className="contact-layout"><div className="contact-details"><a href={`mailto:${profile.email}`} data-analytics-event="contact_click" data-analytics-method="email" data-analytics-location="contact_details"><Mail/><span>Email<small>{profile.email}</small></span><ArrowUpRight/></a><a href={`tel:${profile.phone.replace(/\s/g, '')}`} data-analytics-event="contact_click" data-analytics-method="phone" data-analytics-location="contact_details"><Phone/><span>Phone<small>{profile.phone}</small></span><ArrowUpRight/></a><a href={profile.linkedin} target="_blank" rel="noreferrer" data-analytics-event="social_link_click" data-analytics-platform="linkedin" data-analytics-location="contact_details"><Linkedin/><span>LinkedIn<small>Connect professionally</small></span><ArrowUpRight/></a><div><MapPin/><span>Current location<small>{profile.location}</small></span></div><div><MapPin/><span>Home background<small>{profile.hometown}</small></span></div></div><ContactForm/><aside className="portfolio-qr"><img src={`${import.meta.env.BASE_URL}share/mahesh-portfolio-qr.svg`} alt="QR code opening P. Mahesh Babu's public portfolio" loading="lazy"/><div><p className="eyebrow">PORTFOLIO QR</p><h3>Open the public portfolio.</h3><div className="qr-actions"><a href={`${import.meta.env.BASE_URL}share/mahesh-portfolio-qr.png`} download="P-Mahesh-Babu-Portfolio-QR.png" data-analytics-event="portfolio_share_click" data-analytics-action="download_qr" data-analytics-location="contact_qr">DOWNLOAD QR</a><a href={profile.portfolioUrl} target="_blank" rel="noreferrer" data-analytics-event="portfolio_share_click" data-analytics-action="open_public_site" data-analytics-location="contact_qr">OPEN PUBLIC SITE <ArrowUpRight size={15}/></a></div><small>{profile.portfolioUrl}</small></div></aside></div>
  </section>
}
